<svelte:head>
	<title>Terms of Service — Haveri</title>
</svelte:head>

<div class="legal-page">
	<div class="legal-inner">
		<a href="/" class="back-link">&larr; Home</a>
		<div class="prose">
			<h1>Terms of Service</h1>
			<p><em>Last updated: February 2026</em></p>

			<p>
				These terms govern your use of the Haveri incident management service.
				By using Haveri, you agree to these terms.
			</p>

			<h2>The service</h2>
			<p>
				Haveri provides incident management tooling that integrates with Microsoft Teams.
				The service includes a Teams bot for incident declaration and management, and a
				web dashboard for incident history, analytics, and configuration.
			</p>

			<h2>Your responsibilities</h2>
			<ul>
				<li>You are responsible for the accuracy of information you provide during setup.</li>
				<li>You are responsible for managing access to your Haveri account within your organization.</li>
				<li>You agree not to use the service for any unlawful purpose.</li>
				<li>You are responsible for ensuring that your use of Haveri complies with your organization's policies and applicable regulations.</li>
			</ul>

			<h2>Your data</h2>
			<p>
				You retain ownership of all data you create through Haveri. We do not claim
				ownership of your incident data, timelines, or any content generated by your team.
				See our <a href="/legal/privacy">Privacy Policy</a> for details on how we handle
				your data.
			</p>

			<h2>Service availability</h2>
			<p>
				We aim to keep Haveri available and reliable, but we do not guarantee 100% uptime.
				Haveri depends on third-party services (Microsoft Teams, cloud infrastructure)
				that may experience their own outages. We will communicate any planned maintenance
				in advance.
			</p>

			<h2>Billing</h2>
			<p>
				Subscription fees are billed monthly or annually, depending on your plan.
				Prices are in EUR. We will give at least 30 days' notice before any price changes.
				You can cancel your subscription at any time. Cancellation takes effect at the
				end of the current billing period.
			</p>

			<h2>Limitation of liability</h2>
			<p>
				Haveri is a communication and documentation tool. It does not replace safety
				procedures, regulatory compliance systems, or professional judgment. We are not
				liable for operational decisions made based on information in the system.
			</p>

			<h2>Changes to these terms</h2>
			<p>
				We may update these terms from time to time. We will notify you of significant
				changes via email. Continued use of the service after changes constitutes
				acceptance of the updated terms.
			</p>

			<h2>Contact</h2>
			<p>
				For questions about these terms, contact us at
				<a href="mailto:hello@haveri.app">hello@haveri.app</a>.
			</p>
		</div>
	</div>
</div>

<style>
	.legal-page {
		padding-top: 7rem;
		padding-bottom: 6rem;
	}

	.legal-inner {
		max-width: 680px;
		margin: 0 auto;
		padding: 0 2rem;
	}

	.back-link {
		font-size: 0.82rem;
		color: var(--color-amber);
		text-decoration: none;
		display: inline-block;
		margin-bottom: 2rem;
	}

	.back-link:hover {
		text-decoration: underline;
	}
</style>
