import { expect, test } from '@playwright/test';
import { fixtureForProject } from '../helpers/tenants';

test.describe('Core dashboard workflow', () => {
  test('declares an incident from the dashboard and opens detail view', async ({ page }, testInfo) => {
    const fixture = fixtureForProject(testInfo.project.name);
    const title = `E2E ${fixture.key} ${Date.now().toString(36)}`;

    await page.goto('/');
    await page.locator('#incident-title').fill(title);
    await page.locator('#incident-description').fill('Generated by Playwright E2E test');
    await page.getByRole('button', { name: 'Declare Incident' }).click();

    await expect(page).toHaveURL(/\/incidents\//);
    await expect(
      page.locator('[data-slot="card-title"]').filter({ hasText: title }).first()
    ).toBeVisible();
    await expect(page.getByText('Live Controls')).toBeVisible();
    await expect(
      page.locator('[data-slot="badge"]').filter({ hasText: 'DECLARED' }).first()
    ).toBeVisible();
  });

  test('settings page renders tenant-specific defaults', async ({ page }, testInfo) => {
    const fixture = fixtureForProject(testInfo.project.name);

    await page.goto('/settings');
    await expect(
      page.locator('[data-slot="card-title"]').filter({ hasText: 'Organization Settings' }).first()
    ).toBeVisible();
    await expect(page.locator('#org-name')).toHaveValue(fixture.name);
    await expect(page.locator('#org-slug')).toHaveValue(fixture.slug);
    await expect(
      page.locator('[data-slot="card-title"]').filter({ hasText: 'Facilities' }).first()
    ).toBeVisible();
    await expect(
      page.locator('form[action="?/updateFacility"] input[name="name"]').first()
    ).toHaveValue(fixture.facilityName);
  });
});
